### PR TITLE
Remove deprecated WidevineCdm folder for Chromium 67

### PR DESCRIPTION
**Pull request by bsclifton**
*PLEASE DON'T MERGE UNTIL WE'RE READY FOR Chromium 67*

### CODE REVIEW

**Comment by darkdh** [comment]
is the package-lock change necessary?

**Comment by bbondy** [comment]
@bsclifton does it still work with that change? As I recall the component updater configurator for widevine would copy this file to the profile.  Maybe that's not done anymore.

**Comment by darkdh** [comment]
that is deprecated in C67. the file doesn't exist anymore @bbondy

**Comment by bbondy** [comment]
I just wasn't sure if something else was needed instead or if it's not needed or included in the cdm download now.

**Comment by bsclifton** [comment]
@darkdh yes- package-lock.json changes needed to get rid of a security error brought up on the repo

screen shot 2018-05-24 at 11 21 07 am


@bbondy I'll update the `0.22.x-c67` branch to use this and do a new build so we can confirm it works 😄

**Comment by bsclifton** [comment]
I verified this does work... but unfortunately `npm install` with the dep `brave/muon-winstaller#0.22.x-c67` isn't running the `npm run prepublish` step and so `muon-winstaller` is not aliased as a binary. I can manually run the steps and the `npm run build-installer` works fine.  Not sure of a way to fix this, other than hackery

**Comment by bsclifton** [comment]
work-around in place... doing a build now:
https://github.com/brave/browser-laptop/commit/43abb24df3d3c66ee196853cabab56a73038c051

**Review by bbondy — APPROVED** [review]

**Review by darkdh — APPROVED** [review]

**Pull request merged**
